alias cd.1='cd ..'
alias cs.1='cs ..'
alias cd.2='cd ../..'
alias cs.2='cs ../..'
alias cd.3='cd ../../..'
alias cs.3='cs ../../..'
alias cd.4='cd ../../../..'
alias cs.4='cs ../../../..'
alias cd.5='cd ../../../../..'
alias cs.5='cs ../../../../..'
alias cd.documents='cd $documents'
alias cs.documents='cs $documents'
alias cd.doc='cd.documents'
alias cs.doc='cs.documents'

