
# processes
alias top.xorg='top | egrep -i xorg'
alias top.chrome='top | egrep -i chrome'
#alias ps.xorg='ps cax | egrep "Xorg|^USER" --color'
alias ps.xorg='ps cax | egrep Xorg'
alias ps.chrome='ps cax | egrep -i chrome'
#alias ps.btsync='ps cax | egrep "btsync|^USER " --color'
alias ps.btsync='ps cax | egrep btsync'
alias ps.dropbox='ps cax | egrep -i dropbox'
alias ps.nx='ps cax | egrep -i nxserver'
alias ps.vlc='ps cax | egrep -i vlc'
alias ps.fcitx='ps cax | egrep -i fcitx'
alias ps.thunderbird='ps cax | egrep -i thunderbird'
alias ps.tb='ps.thunderbird'
alias ps.autokey='ps cax | egrep -i autokey'
