alias halt.0='shutdown -h now'
alias suhalt.0='sudo shutdown -h now'
alias halt.1='shutdown -h +1'
alias suhalt.1='sudo shutdown -h +1'
alias halt.2='shutdown -h +2'
alias suhalt.2='sudo shutdown -h +2'
alias halt.3='shutdown -h +3'
alias suhalt.3='sudo shutdown -h +3'
alias halt.4='shutdown -h +4'
alias suhalt.4='sudo shutdown -h +4'
alias halt.5='shutdown -h +5'
alias suhalt.5='sudo shutdown -h +5'
alias halt.10='shutdown -h +10'
alias suhalt.10='sudo shutdown -h +10'
alias halt.15='shutdown -h +15'
alias halt.20='shutdown -h +20'
alias suhalt.20='sudo shutdown -h +20'
alias halt.25='shutdown -h +25'
alias suhalt.25='sudo shutdown -h +25'
alias halt.30='shutdown -h +30'
alias suhalt.30='sudo shutdown -h +30'
alias halt.40='shutdown -h +40'
alias suhalt.40='sudo shutdown -h +40'
alias halt.50='shutdown -h +50'
alias suhalt.50='sudo shutdown -h +50'
alias halt.60='shutdown -h +60'
alias suhalt.60='sudo shutdown -h +60'
alias halt.120='shutdown -h +120'
alias suhalt.120='sudo shutdown -h +120'

alias suhibernate='sudo pm-hibernate'
alias sususpend='sudo pm-suspend'



