# ssh
alias ssh.auth_sock0='export SSH_AUTH_SOCK=0'
alias ssh.l10='ssh -p $ssh_port $nixuser@$l10'
alias ssh.l11='ssh -p $ssh_port $nixuser@$l11'
alias ssh.i1='ssh -p $ssh_port $nixuser@$i1'
alias ssh.i2='ssh -p $ssh_port $nixuser@$i2'
alias ssh.i3='ssh -p $ssh_port $nixuser@$i3'
alias ssh.i4='ssh -p $ssh_port $nixuser@$i4'
alias ssh.y570='ssh -p $ssh_port $nixuser@$y570'
alias ssh.y450='ssh -p $ssh_port $nixuser@$y450'
alias ssh.home='ssh -p $ssh_port $nixuser@$homeip'
alias ssh.nb205='ssh -p $ssh_port $nixuser@$nb205'
alias ssh.s07='ssh -p 22 lisa1107@$s07'
alias ssh.s08='ssh -p 22 lisa1107@$s08'
alias ssh.econ3='ssh -p 22 lisa1107@$econ3'
alias ssh.s3='ssh -p 46904 dclong@$s3'
alias ssh.ubsas='ssh -p 22 $nixuser@${ubsas}'
alias ssh.boasas='ssh -p 22 $nixuser@$boasas'
alias ssh.sasgrid='ssh -p 22 $nixuser@$sasgrid'
# diff using ssh
alias diff.y570='diff.server $nixuser@$y570 $ssh_port'
alias diff.home='diff.server $nixuser@$homeip $ssh_port'
alias diff.nb205='diff.server $nixuser@$nb205 $ssh_port'

alias ssh-copy-id.l11='ssh-copy-id -i ${HOME}/.ssh/id_rsa.pub "$nixuser@$l11 -p $ssh_port"'
alias ssh-copy-id.l10='ssh-copy-id -i ${HOME}/.ssh/id_rsa.pub "$nixuser@$l10 -p $ssh_port"'
alias ssh-copy-id.y570='ssh-copy-id -i ${HOME}/.ssh/id_rsa.pub "$nixuser@$y570 -p $ssh_port"'
alias ssh-copy-id.econ3='ssh-copy-id -i ${HOME}/.ssh/id_rsa.pub "lisa1107@$econ3 -p $ssh_port"'


