# tmux
alias tmux='tmux -2'
alias tmux.att='tmux attach'
alias tmux.det='tmux detach'
alias tmux.ks='tmux kill-session'
alias tmux.nw='tmux neww'
alias tmux.rw='tmux rotatew'
alias tmux.spw='tmux splitw'
alias tmux.spwh='tmux splitw -v'
alias tmux.spwv='tmux splitw -h'
alias tmux.sew='tmux selectw'
alias tmux.kw='tmux killw'
alias tmux.np='tmux newp'
alias tmux.kp='tmux killp'
alias tmux.sp='tmux selectp'
alias tmux.spt='tmux selectp -t'
alias tmux.spr='tmux selectp -R'
alias tmux.spl='tmux selectp -L'
alias tmux.spu='tmux selectp -U'
alias tmux.spd='tmux selectp -D'
alias tmux.lsp='tmux listp'
alias tmux.lsw='tmux lsw'
alias tmux.dp='tmux displayp'
alias tmux.bp='tmux breakp'
alias tmux.sf='tmux source-file'
#alias tmux.notes='xfce4-terminal -T notes --hide-toolbars --hide-menubar --hide-borders --maximize --command="tmux new-session -s notes"'

