name: release
on:
  push:
    tags: ["v*"]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install Poetry
        run: |
          pip3 install -U xinstall
          xinstall pt -ic
      - name: Build and Publish Package to PyPI
        run: |
          ~/.local/bin/poetry publish --build -u __token__ -p ${{ secrets.PYPI_XINSTALL }}
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            dist/*
